import { beforeEach, describe, expect, test } from 'bun:test'
import { advanceWeek, createGame, loadGame, rolloverSeason, SAVE_KEY } from '../src/game'

const memory = new Map<string, string>()
Object.assign(globalThis, {
  localStorage: {
    setItem: (key: string, value: string) => memory.set(key, value),
    getItem: (key: string) => memory.get(key) ?? null,
    removeItem: (key: string) => memory.delete(key),
  },
})
beforeEach(() => memory.clear())

describe('season rollover', () => {
  test('players age and contract years count down', () => {
    const state = createGame('Manager', 'c9')
    const before = structuredClone(state.players)
    rolloverSeason(state)
    expect(state.season).toBe(2027)
    expect(state.week).toBe(1)
    Object.values(state.players).forEach((player) => {
      expect(player.age).toBe(before[player.id].age + 1)
      if (before[player.id].teamId && before[player.id].years > 1)
        expect(player.years).toBe(before[player.id].years - 1)
    })
  })

  test('Championship Points and season records reset', () => {
    const state = createGame('Manager', 'c9')
    Object.values(state.teams).forEach((team) => {
      team.championshipPoints = 7
      team.wins = 4
      team.losses = 2
      team.mapWins = 9
      team.mapLosses = 5
    })
    rolloverSeason(state)
    Object.values(state.teams).forEach((team) => {
      expect(team.championshipPoints).toBe(0)
      expect([team.wins, team.losses, team.mapWins, team.mapLosses]).toEqual([0, 0, 0, 0])
    })
  })

  test('expired managed contracts leave unless needed to field five', () => {
    const state = createGame('Manager', 'c9')
    const team = state.teams.c9
    const [bench1, bench2] = ['tier2-0', 'tier2-1']
    ;[bench1, bench2].forEach((id) => {
      team.playerIds.push(id)
      Object.assign(state.players[id], { teamId: 'c9', status: 'substitute', years: 3 })
    })
    const expiring = team.lineup.slice(0, 3)
    team.playerIds.forEach((id) => {
      if (!expiring.includes(id) && id !== bench1 && id !== bench2) state.players[id].years = 3
    })
    expiring.forEach((id) => {
      state.players[id].years = 1
    })
    rolloverSeason(state)
    // Seven players, three expire: two may walk, one re-signs to keep five.
    expect(team.playerIds).toHaveLength(5)
    expect(team.lineup).toHaveLength(5)
    expect(team.lineup.every((id) => team.playerIds.includes(id))).toBeTrue()
    const walked = expiring.filter((id) => !team.playerIds.includes(id))
    expect(walked).toHaveLength(2)
    walked.forEach((id) => {
      expect(state.players[id].teamId).toBeNull()
      expect(state.players[id].status).toBe('free-agent')
    })
    const stayed = expiring.find((id) => team.playerIds.includes(id))!
    expect(state.players[stayed].years).toBeGreaterThan(0)
    expect(state.inbox.some((line) => line.startsWith('Contracts expired'))).toBeTrue()
  })

  test('AI teams keep their expiring starters', () => {
    const state = createGame('Manager', 'c9')
    const team = state.teams.fnc
    team.lineup.forEach((id) => {
      state.players[id].years = 1
    })
    rolloverSeason(state)
    expect(team.lineup).toHaveLength(5)
    team.lineup.forEach((id) => {
      expect(state.players[id].teamId).toBe('fnc')
      expect(state.players[id].years).toBeGreaterThan(0)
    })
  })

  test('every roster stays legal after a full season', { timeout: 15000 }, () => {
    let state = createGame('Manager', 'c9')
    const ages = Object.fromEntries(Object.values(state.players).map((p) => [p.id, p.age]))
    for (let week = 0; week < 52; week++)
      state = advanceWeek(state, 'Measured defaults', 'Disciplined retakes')
    expect(state.season).toBe(2027)
    expect(
      state.inbox.some((line) => line.startsWith('Contracts expiring after season 2026')),
    ).toBeTrue()
    Object.values(state.teams).forEach((team) => {
      expect(team.championshipPoints).toBe(0)
      expect(team.playerIds.length).toBeGreaterThanOrEqual(5)
      expect(team.lineup).toHaveLength(5)
      team.playerIds.forEach((id) => {
        expect(state.players[id].years).toBeGreaterThan(0)
        expect(state.players[id].teamId).toBe(team.id)
      })
    })
    // Prospects generated by in-season transfer windows were not in the starting pool.
    Object.values(state.players)
      .filter((player) => player.id in ages)
      .forEach((player) => {
        expect(player.age).toBe(ages[player.id] + 1)
      })
    const rolloverMoves = state.transfers.filter(
      (move) => move.season === 2027 && (move.kind === 'expiry' || move.kind === 'renewal'),
    )
    expect(rolloverMoves.length).toBeGreaterThan(0)
  })

  test('older saves gain player ages on load', () => {
    const state = createGame('Manager', 'c9') as unknown as {
      version: number
      players: Record<string, { age?: number }>
    }
    state.version = 8
    Object.values(state.players).forEach((player) => {
      delete player.age
    })
    memory.set(SAVE_KEY, JSON.stringify(state))
    const loaded = loadGame()!
    expect(loaded.version).toBe(12)
    Object.values(loaded.players).forEach((player) => {
      expect(player.age).toBeGreaterThanOrEqual(17)
    })
  })
})
